admin_panel/urls.py
from django.urls import path
from admin_sample.views import (index, user_login, user_dashboard, seller_login, seller_dashboard,user_signup,seller_signup,seller_logout,user_logout,
                                user_order_list
                                )

urlpatterns = [
    path('',index,name="index"),
    path('user_login',user_login,name="user_login"),
    path('user_dashboard',user_dashboard,name="user_dashboard"),
    path('seller_login',seller_login,name="seller_login"),
    path('seller_dashboard',seller_dashboard,name="seller_dashboard"),
    path('user_signup',user_signup,name="user_signup"),
    path('seller_signup',seller_signup,name="seller_signup"),
    path('seller_logout',seller_logout,name="seller_logout"),
    path('user_logout',user_logout,name="user_logout"),
    path('user_order_list',user_order_list,name="user_order_list"),
]

admin_sample/models.py
from django.db import models

# Create your models here.
class OrderDetailsModel(models.Model):
    order_no=models.CharField( max_length=50)
    name =models.CharField(max_length=50)
    quantity =models.IntegerField()
    price= models.DecimalField(decimal_places =2,max_digits=10)
    pin= models.CharField(max_length=50)
    class Meta:
        db_table='tbl_order_details'


class UserDetailsModel(models.Model):
    username_name =models.CharField(max_length=50)
    address= models.CharField(max_length=50)
    username =models.CharField(max_length=10)
    password=models.CharField(max_length=20)
    class Meta:
        db_table='tbl_user'

class SellerDetailsModel(models.Model):
    seller_name =models.CharField(max_length=50)
    state_name= models.CharField(max_length=50)
    pin  = models.CharField(max_length=50)
    username =models.CharField(max_length=10)
    password=models.CharField(max_length=20)
    class Meta:
        db_table='tbl_seller'

class OrderStatusModel(models.Model):
    order= models.ForeignKey(OrderDetailsModel, on_delete=models.CASCADE)
    user = models.ForeignKey(UserDetailsModel, on_delete=models.CASCADE)
    seller  = models.ForeignKey(SellerDetailsModel, on_delete=models.CASCADE)
    seller_action = models.SmallIntegerField( null=True)
    remark = models.CharField(max_length=50, null=True)

    class Meta:
        db_table ='tbl_order_status'

admin_sample/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import HttpResponse,render,redirect
from .models import *
from django.contrib import messages

def index(request):
    return render(request,"index.html")

def user_login(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password =request.POST.get('password')

        check_pass=UserDetailsModel.objects.filter(username=username,password=password).first()
        if check_pass:
            request.session['username']=check_pass.username
            request.session['user_id']=check_pass.id
            orders_list=OrderStatusModel.objects.all()
            messages.success(request,"Successfully Login")
            return redirect('user_dashboard')
        else:
            messages.error("This user does not exits ")
    else:
        if request.session.get('username'):
            return redirect('user_dashboard')
    return render(request,'user_login.html',)

def user_signup(request):
    if request.method=="POST":
        name=request.POST['name']
        address= request.POST['address']
        username=request.POST['username']
        password=request.POST['password']
        found=UserDetailsModel.objects.filter(username=username)
        if found :
            messages.error(request,"This username not available")
        else:
            create_user=UserDetailsModel.objects.create(
                username_name=name,
                address=address,
                username=username,
                password=password,
            )
            if create_user:
                messages.error(request,"User Created")
    return render(request,'user_signup.html')

def user_logout(request):
    if "username" in request.session:
        del request.session["username"]
    if "user_id" in request.session:
        del request.session["user_id"]
    messages.success(request,"Successfully Logout")
    return redirect('/')

def user_dashboard(request):
    if request.session.get('username'):
        user_id=request.session.get('user_id')
        if request.method == 'POST':
            pin =request.POST.get('pin')
            sel_det=SellerDetailsModel.objects.filter(pin=pin).first()
            if not sel_det:
                messages.error(request,"Seller Not Exist for this pin")
                return render(request,'user_dashboard.html')
            order_no=request.POST.get('order_no')
            found=OrderDetailsModel.objects.filter(order_no=order_no)
            if found:
                messages.error(request,'This order no already exist')
                return redirect('user_dashboard')
            ord=OrderDetailsModel.objects.create(
                order_no=order_no,
                name=    request.POST.get('name'),
                quantity= request.POST.get('quantity'),
                price= request.POST.get('price'),
                pin= pin ,
            )
            order_state_created=OrderStatusModel.objects.create(order_id = ord.id ,seller_id =sel_det.id,user_id= user_id)
            if order_state_created:
                messages.error(request,"Order Created")
    else:
        return redirect('user_dashboard')
    return render(request,'user_dashboard.html')


def user_order_list(request):
    orders_list=''
    if request.session.get('seller_username'):
        user_id=request.session['seller_id']
        orders_list=OrderStatusModel.objects.filter(user_id=user_id)
    return render(request,"user_order_list.html",{'orders_list':orders_list})

def seller_login(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password =request.POST.get('password')
        check_pass=SellerDetailsModel.objects.filter(username=username,password=password).first()
        if check_pass:
            request.session['seller_username']=check_pass.username
            request.session['seller_id']=check_pass.id
            return redirect('seller_dashboard')
        else:
            messages.error(request,"This seller does not exits ")
    else:
        if request.session.get('seller_username'):
            return redirect('seller_dashboard')
    return render(request,'seller_login.html',)

def seller_signup(request):
    if request.method=="POST":
        name=request.POST['name']
        state_name= request.POST['state']
        pin=request.POST['pin']
        username=request.POST['username']
        password=request.POST['password']
        found =SellerDetailsModel.objects.filter(username=username)
        if found:
            messages.error(request,"This username not available")
        else:
            create_user=SellerDetailsModel.objects.create(
                seller_name=name,
                state_name=state_name,
                pin=pin,
                username=username,
                password=password,
            )
            if create_user:
                messages.error(request,"Seller created")
    return render(request,'seller_signup.html')


def seller_logout(request):
    if "seller_username" in request.session:
        del request.session["seller_username"]
    if "seller_id" in request.session:
        del request.session["seller_id"]
    messages.success(request,"Successfully Logout")
    return redirect('/')

def seller_dashboard(request):
    orders_list=''
    if request.session.get('seller_username'):
        seller_id=request.session['seller_id']
        orders_list=OrderStatusModel.objects.filter(seller_id=seller_id)
        if request.method=='POST':
            if  "btn_acsubmit" in request.POST :
                btn_value=request.POST["btn_acsubmit"]
                order_id=request.POST[f"order{btn_value}"]
                OrderStatusModel.objects.filter(order_id=order_id).update(
                    seller_action= 1,
                    remark= "Accepted"
                )
                return redirect('seller_dashboard')
            
            if  "btn_rjsubmit" in request.POST :
                btn_value=request.POST["btn_rjsubmit"]
                order_id=request.POST[f"order{btn_value}"]
                remark=request.POST[f"remark{btn_value}"]
                OrderStatusModel.objects.filter(order_id=order_id).update(
                    seller_action= 2,
                    remark= remark
                )
                return redirect('seller_dashboard')
    else:
        return redirect('seller_login')
    return render(request,'seller_dashboard.html',{"orders_list":orders_list})

templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock title %}</title>
  <!-- Bootstrap CSS -->
  {% comment %} <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"> {% endcomment %}
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  {% comment %} <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"> {% endcomment %}
  <style>
    body {
      font-family: 'Arial', sans-serif;
      line-height: 1.6;
    }

    .hero {
      background: linear-gradient(to right, #6a11cb, #2575fc);
      color: white;
      padding: 60px 0;
    }

    .hero h1 {
      font-size: 3rem;
    }

    .hero p {
      font-size: 1.2rem;
    }

    .content-section {
      padding: 40px 0;
    }

    .footer {
      background-color: #343a40;
      color: white;
      padding: 20px 0;
      
      
      position: sticky;
      
      width: 100%;
    }

    .footer a {
      color: #adb5bd;
      text-decoration: none;
    }

    .footer a:hover {
      color: #ffffff;
    }


    input.error {
      background-color: #ffa8a8;
      border: 1px dotted red;
  }

  input.error:focus { 
      background-color: #ffa8a8;
      border: 1px dotted red;
  }

  input.error {
      display: inline !important;
  }

  input.error {
    display: inline !important;
}

  .error{
    color:red;
    width:100%;
    margin-top:10px;
    padding-left:10px;
  }

  .errors{
    color:red;
    width:100%;
    margin-top:1px;
    padding-left:10px;
  }
  </style>
</head>
<body>
  <!-- Header -->
  <header class="bg-info py-3">
    <div class="container d-flex justify-content-between align-items-center">
      <h1 class="h4">Admin Panel</h1>
      <nav>
        <ul class="nav">
          <li class="nav-item">
            <a class="nav-link text-dark" href="/">Home</a>
          </li>
          <li class="nav-item">
            {% comment %} <a class="nav-link text-dark" href="/user_login">User Login</a> {% endcomment %}
            <a class="nav-link text-dark" href={% if request.session.username %}"/user_logout" {% else %}"/user_login" {% endif %}>{% if request.session.username %}User Logout {% else %}User Login {% endif %}</a>

          </li>
          {% if request.session.username %}
          <li class="nav-item">
            <a class="nav-link text-dark" href="/user_dashboard" >User Dashboard </a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link text-dark" href={% if request.session.seller_username %}"/seller_logout" {% else %}"/seller_login" {% endif %}>{% if request.session.seller_username %}Seller Logout {% else %}Seller Login {% endif %}</a>
          </li>
          {% if request.session.seller_username %}
          <li class="nav-item">
            <a class="nav-link text-dark" href="/seller_dashboard" >Seller Dashboard </a>
          </li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </header>
  {% comment %} {% if messages %} {% endcomment %}
    {% for message in messages %} 
    <h3 class="class alert alert-danger">{{message}}</h3>
    {% endfor %} 
  {% comment %} {% endif %} {% endcomment %}
  {% block main_content %}{% endblock main_content %}
  <!-- Footer -->
  <footer class="bd-footer py-5 mt-5 bg-dark footer">
    <div class="container text-center">
      <p>&copy; 2024 Admin Panel. All Rights Reserved.</p>
      <ul class="list-inline">
        <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
        <li class="list-inline-item"><a href="#">Terms of Use</a></li>
        <li class="list-inline-item"><a href="#">Contact</a></li>
      </ul>
    </div>
  </footer>

  <!-- Bootstrap JS -->
  {% comment %} <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" ></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js" ></script> {% endcomment %}
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
  <script src="{% static 'js/jquery.validate.min.js' %}"></script>
{% block script %}{% endblock script %}

</body>
</html>

templates/index.html
{% extends "base_layout.html" %}

{% block title %}Index{% endblock title %}

{% block main_content %}
<!-- Hero Section -->
<section class="hero text-center">
  <div class="container">
    <h1>Welcome to Admin Panel</h1>
    
    
  </div>
</section>

<!-- Content Section -->
<section class="content-section">
  <div class="container">
    <div class="row text-center">

      <div class="col-lg-6 mb-6">
        <div class="card shadow-sm">
          <div class="card-body">
            <h5 class="card-title">User Login</h5>
            <p class="card-text">Click below button if you want to login as user.</p>
            <a href="/user_login" class="btn btn-outline-primary">Click</a>
          </div>
        </div>
      </div>

      <div class="col-lg-6 mb-6">
        <div class="card shadow-sm">
          <div class="card-body">
            <h5 class="card-title">Seller Login</h5>
            <p class="card-text">Click below button if you want to login as seller.</p>
            <a href="/seller_login" class="btn btn-outline-primary">Click</a>
          </div>
        </div>
      </div>

 

    </div>
  </div>
</section>

{% endblock main_content %}

templates/seller_dashboard.html
 
{% extends "base_layout.html" %}

{% block title %}Seller Dashboard{% endblock title %}

{% block main_content %}

<!-- Content Section -->
<section class="content-section m-3" >
    <h1 class="text text-center">Seller Dashboard</h1>
    <table class="table">     
        <tr>
        <td class="table-active">Order No.</td>
        <td class="table-active">Name</td>
        <td class="table-active">Quantity</td>
        <td class="table-active">Price</td>
        <td class="table-active">Action</td>
        <td class="table-active">Remark</td>
        </tr>
        {% for data in orders_list  %}
        <tr>
          <td>{{data.order.order_no}}</th>
          <td >{{data.order.name}}</td>
          <td>{{data.order.quantity}}</td>
          <td>{{data.order.price}}</td>
          <td>
              {% if data.seller_action is None %}
              <button  name="accept" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#acceptModal{{data.order.id}}" >Accept</button>
              <!-- Button trigger modal -->
                {{data.seller_action}}
              <button type="submit" name="reject" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#RejectModal{{data.order.id}}">Reject</button>
              {% elif  data.seller_action is 1 %}
                <span class="text text-success"> Accepted </span>
              {% elif data.seller_action is 2 %}
                <span class="text text-danger"> Rejected </span>
              {% endif %}
              
              <!--Accept Modal  start-->
              <div class="modal fade" id="acceptModal{{data.order.id}}" tabindex="-1" aria-labelledby="acceptModalLabel" aria-hidden="true">
                  <div class="modal-dialog">
                  <div class="modal-content">
                      <div class="modal-header">
                      <h5 class="modal-title" id="acceptModalLabel">Are you sure accept this order?</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <form method="POST" >
                          {% csrf_token %}
                      <div class="modal-body">
                      
                      </div>
                      <div class="modal-footer">
                      <input type="hidden" name="order{{data.order.id}}" value="{{data.order.id}}">
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                      <button type="submit" class="btn btn-primary" name="btn_acsubmit" value="{{data.order.id}}">Accept</button>
                      </div>
                      </form>
                  </div>
                  </div>
              </div>
              <!--Accept Modal  end-->

              
              <!--Reject Modal  start-->
              <div class="modal fade" id="RejectModal{{data.order.id}}" tabindex="-1" aria-labelledby="RejectModalLabel" aria-hidden="true">
                  <div class="modal-dialog">
                  <div class="modal-content">
                      <div class="modal-header">
                      <h5 class="modal-title" id="RejectModalLabel">Are you sure reject this order?</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <form method="POST" id="iform">
                          {% csrf_token %}
                      <div class="modal-body">
                      
                      <label for="id_remark" class="form-label">Reason For Reject</label>
                      <input type='text' class="form-control" required="true" name="remark{{data.order.id}}" id="id_remark{{data.order.id}}"/>
                      </div>
                      <div class="modal-footer">
                          <input type="hidden" name="order{{data.order.id}}" value="{{data.order.id}}">    
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                      <button type="submit" class="btn btn-primary" name="btn_rjsubmit" value="{{data.order.id}}">Reject</button>
                      </div>
                      </form>
                  </div>
                  </div>
              </div>
              <!--Reject Modal  end-->
          </td>
          <td>{{data.remark}}</td>
        </tr>
        {% endfor %}
      
    </table>
</section>

{% endblock main_content %}

{% block script %}
<script >
    jQuery('#iform').validate({
  rules:{
      order_no:"required",
      name:"required",
      quantity:"required",
      price:"required",
      pin:"required",
      },
   messages:{
      order_no:"Please enter Order No", 
      name:  "Please enter Name",
      quantity: "Please enter Quantity",
      price:"Please enter Price",
      pin:"Please entet Pin",
      },
});
   </script> 
{% endblock script %}

templates/seller_login.html
{% extends "base_layout.html" %}

{% block title %}Seller Login{% endblock title %}

{% block main_content %}

<!-- Content Section -->
<section class="content-section m-3" >
    <h1 class="text text-center">Seller Login</h1>
    <div class="container">
      <div class="row justify-content-center">
    <form  method="post" id="iform" >
        {% csrf_token %}
        
        <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input type="text" class="form-control" id="username" name="username">
          </div>
          <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password" class="form-control" id="password" name="password">
          </div>
          <a href="/seller_signup"> Sign Up</a>

        <div class="col-12" align='center'>
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </div>
    
    </form>
  </div>
</section>

{% endblock main_content %}

{% block script %}
<script >
    jQuery('#iform').validate({
  rules:{
      username:"required",
      password:"required",
      
      },
   messages:{
      username:"Please enter Username", 
      password:  "Please enter Name",
      
      },
});
   </script> 
{% endblock script %}

templates/seller_signup.html
{% extends "base_layout.html" %}

{% block title %}Seller SignUp{% endblock title %}

{% block main_content %}

<!-- Content Section -->
<section class="content-section m-3" >
    <h1 class="text text-center">Seller Singup</h1>
    <form class="row g-3" method="post" id="iform" >
        {% csrf_token %}

        <div class="mb-3">
            <label for="name" class="form-label">Name</label>
            <input type="text" class="form-control" id="name" name="name">
        </d>
        <div class="mb-3">
            <label for="state" class="form-label">State</label>
            <input type="text" class="form-control" id="state" name="state">
        </div>
        <div class="mb-3">
            <label for="pin" class="form-label">Pin</label>
            <input type="text" class="form-control" id="pin" name="pin">
        </div>
        <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input type="text" class="form-control" id="username" name="username">
          </div>
          <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password" class="form-control" id="password" name="password">
          </div>
         

        <div class="col-12" align='center'>
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</section>

{% endblock main_content %}

{% block script %}
<script >
    jQuery('#iform').validate({
    rules:{
        name:"required",
        address:"required",
        pin:"required",
        username:"required",
        password:"required",
        },
   messages:{
    name:"Please enter Name",
    address:"Please enter Address",
    pin:"Please enter Pin",
      username:"Please enter Username", 
      password:  "Please enter Name",
      
      },
});
   </script> 
{% endblock script %}

templates/user_dashboard.html
{% extends "base_layout.html" %}

{% block title %}User Dashboard{% endblock title %}

{% block main_content %}

<!-- Content Section -->
<section class="content-section m-3" >
    <h1 class="text text-center">User Dashboard</h1>
    <h6 class="text text-center"> <a href="/user_order_list">Orders List </a></h6>
    <form class="row g-3" method="post" id="iform" >
      {% csrf_token %}
      <div class="col-md-6">
        <label for="order_no" class="form-label">Order No.</label>
        <input type="text" class="form-control" id="order_no" name="order_no">
      </div>
      <div class="col-md-6">
        <label for="name" class="form-label">Name</label>
        <input type="text" class="form-control" id="name" name="name">
      </div>

      <div class="col-md-4">
          <label for="quantity" class="form-label">Quantity</label>
          <input type="number" class="form-control" step="1" id="quantity" name="quantity">
        </div>
        <div class="col-md-4">
          <label for="price" class="form-label">Price</label>
          <input type="number" class="form-control" id="price" name="price">
        </div>

        <div class="col-md-4">
          <label for="pin" class="form-label">Pin</label>
          <input type="text" class="form-control" id="pin" name="pin">
        </div>

      <div class="col-12" align='center'>
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
  </form>
</section>

{% endblock main_content %}

{% block script %}
<script >
    jQuery('#iform').validate({
    rules:{
      order_no:"required",
      name:"required",
        address:"required",
        pin:"required",
        quantity:"required",
        price:"required",
        },
   messages:{
    order_no:"Please enter Order No.",
    name:"Please enter Name",
    address:"Please enter Address",
    pin:"Please enter Pin",
      quantity:"Please enter Quantity without decimal point", 
      price:  "Please enter price",
      
      },
});
   </script> 
{% endblock script %}

templates/user_login.html
{% extends "base_layout.html" %}

{% block title %}User Login{% endblock title %}

{% block main_content %}

<!-- Content Section -->
<section class="content-section m-3" >
    <h1 class="text text-center">User Login</h1>
    
    <div class="container">
      <div class="row justify-content-center">
    <form   method="post" id="iform" >
        {% csrf_token %}
      
        <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input type="text" class="form-control" id="username" name="username">
          </div>
          <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password" class="form-control" id="password" name="password">
          </div>
          <a href="/user_signup"> Sign Up</a>

        <div class="col-12" align='center'>
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
  </div>
</div>
</section>

{% endblock main_content %}

{% block script %}
<script >
    jQuery('#iform').validate({
  rules:{
      username:"required",
      password:"required",
      
      },
   messages:{
      username:"Please enter Username", 
      password:  "Please enter Name",
      
      },
});
   </script> 
{% endblock script %}

templates/user_order_list.html
 
{% extends "base_layout.html" %}

{% block title %}Order List{% endblock title %}

{% block main_content %}

<!-- Content Section -->
<section class="content-section m-3" >
    <table class="table">     
        <tr>
        <td class="table-active">Order No.</td>
        <td class="table-active">Name</td>
        <td class="table-active">Quantity</td>
        <td class="table-active">Price</td>
        <td class="table-active">Action Done By Seller</td>
        <td class="table-active">Remark</td>
        </tr>
        {% for data in orders_list  %}
        <tr>
          <td>{{data.order.order_no}}</th>
          <td >{{data.order.name}} </td>
          <td>{{data.order.quantity}}</td>
          <td>{{data.order.price}}</td>
          <td>
              {% if data.seller_action is None %}
                <span class="text text-primary">Pending </span>
              {% elif  data.seller_action is 1 %}
              <span class="text text-success"> Accepted </span>
              {% elif data.seller_action is 2 %}
              <span class="text text-danger"> Rejected </span>
              {% endif %}
          </td>
          <td>{{data.remark}}</td>
        </tr>
        {% endfor %}
      
    </table>
</section>

{% endblock main_content %}

{% block script %}
<script >
    jQuery('#iform').validate({
  rules:{
      order_no:"required",
      name:"required",
      quantity:"required",
      price:"required",
      pin:"required",
      },
   messages:{
      order_no:"Please enter Order No", 
      name:  "Please enter Name",
      quantity: "Please enter Quantity",
      price:"Please enter Price",
      pin:"Please entet Pin",
      },
});
   </script> 
{% endblock script %}

templates/user_signup.html
{% extends "base_layout.html" %}

{% block title %}User SignUp{% endblock title %}

{% block main_content %}

<!-- Content Section -->
<section class="content-section m-3" >
    <h1 class="text text-center">User SignUp</h1>
    <form class="row g-3" method="post" id="iform" >
        {% csrf_token %}

        <div class="mb-3">
            <label for="name" class="form-label">Name</label>
            <input type="text" class="form-control" id="name" name="name">
        </div>
        <div class="mb-3">
            <label for="address" class="form-label">Address</label>
            <input type="text" class="form-control" id="address" name="address">
        </div>
            <label for="username" class="form-label">Username</label>
            <input type="text" class="form-control" id="username" name="username">
          </div>

          
          <div class="mb-4">
            <label for="password" class="form-label">Password</label>
            <input type="password" class="form-control" id="password" name="password">
          </div>
          

        <div class="col-12" align='center'>
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</section>

{% endblock main_content %}

{% block script %}
<script >
    jQuery('#iform').validate({
    rules:{
        name:"required",
        address:"required",
        username:"required",
        password:"required",
        },
   messages:{
    name:"Please enter Name",
    address:"Please enter Address",
      username:"Please enter Username", 
      password:  "Please enter Name",
      
      },
});
   </script> 
{% endblock script %}